apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: simple-app
spec:
  components:
    - componentName: stateless-component
      instanceName: demo
      traits:
        - name: manual-scaler
          properties:
            replicaCount: 2
