apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hc-oam-controller-role
rules:
  - apiGroups: ["", "apps", "batch", "extensions", "autoscaling", "core.oam.dev", "apiextensions.k8s.io", "harmonycloud.cn", "mysql.middleware.harmonycloud.cn"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hc-oam-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hc-oam-controller-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: oam-system
