apiVersion: core.oam.dev/v1alpha1
kind: Trait
metadata:
  name: resources-policy
  annotations:
    version: v1.0.0
    description: "ResourcesPolicy Trait used for components to limit container's resources."
spec:
  appliesTo:
    - core.oam.dev/v1alpha1.Server
    - core.oam.dev/v1alpha1.SingletonServer
    - core.oam.dev/v1alpha1.Worker
    - core.oam.dev/v1alpha1.SingletonWorker
    - core.oam.dev/v1alpha1.Task
    - core.oam.dev/v1alpha1.SingletonTask
  properties: |
    {
        "$schema":"http://json-schema.org/draft-07/schema#",
        "type":"object",
        "required":[
            "container",
            "limits"
        ],
        "properties":{
            "container":{
                "type":"string",
                "description":"The container name."
            },
            "limits":{
                "type":"map",
                "description":"Limits describes the maximum amount of compute resources allowed."
            }
        }
    }