apiVersion: core.oam.dev/v1alpha1
kind: Trait
metadata:
  name: volume-mounter
  annotations:
    version: v1.0.0
    description: "The volume mounter trait is responsible for attaching a Kubernetes PersistentVolume Claim(PVC) to a component."
spec:
  appliesTo:
    - core.oam.dev/v1alpha1.Server
    - core.oam.dev/v1alpha1.SingletonServer
    - core.oam.dev/v1alpha1.Worker
    - core.oam.dev/v1alpha1.SingletonWorker
    - core.oam.dev/v1alpha1.Task
    - core.oam.dev/v1alpha1.SingletonTask
  properties: |
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "volumeName",
        "storageClass"
      ],
      "properties": {
        "volumeName": {
          "type": "string",
          "description": "The name of the volume this backs. This matches the volume name declared in the ComponentSchematic."
        },
        "storageClass": {
          "type": "string",
          "description": "The storage class that a PVC requires."
        }
      }
    }