apiVersion: core.oam.dev/v1alpha1
kind: Trait
metadata:
  name: schedule-policy
  annotations:
    version: v1.0.0
    description: "SchedulePolicy Trait used to schedule instance's pods to expect nodes."
spec:
  appliesTo:
    - core.oam.dev/v1alpha1.Server
    - core.oam.dev/v1alpha1.SingletonServer
    - core.oam.dev/v1alpha1.Worker
    - core.oam.dev/v1alpha1.SingletonWorker
    - core.oam.dev/v1alpha1.Task
    - core.oam.dev/v1alpha1.SingletonTask
  properties: |
    {
        "$schema":"http://json-schema.org/draft-07/schema#",
        "type":"object",
        "properties":{
            "nodeAffinity":{
                "type":"object",
                "description":"Describes node affinity scheduling rules for the instance's pod.",
                "properties":{
                    "type":{
                        "type":"string",
                        "default":"preferred",
                        "description":"Describes the affinity type, value: required, preferred."
                    },
                    "selector":{
                        "type":"map",
                        "description":"The selector for the nodeAffinity"
                    }
                }
            },
            "podAffinity":{
                "type":"object",
                "description":"Describes pod affinity scheduling rules.",
                "properties":{
                    "type":{
                        "type":"string",
                        "default":"preferred",
                        "description":"Describes the affinity type, value: required, preferred."
                    },
                    "selector":{
                        "type":"map",
                        "description":"The selector for the podAffinity"
                    }
                }
            },
            "podAntiAffinity":{
                "type":"object",
                "description":"Describes pod anti-affinity scheduling rules.",
                "properties":{
                    "type":{
                        "type":"string",
                        "default":"preferred",
                        "description":"Describes the affinity type, value: required, preferred."
                    },
                    "selector":{
                        "type":"map",
                        "description":"The selector for the podAntiAffinity"
                    }
                }
            }
        }
    }