apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: nginx-replicated-v1
spec:
  workloadType: core.oam.dev/v1alpha1.Server
  containers:
    - image: nginx:latest
      name: server
      ports:
        - containerPort: 80                  # <-- this is the service port
          name: http
          protocol: TCP