apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: mysql-cluster
  annotations:
    group: harmonycloud.cn/v1alpha1
    version: v1.0.0
    description: "MysqlCluster workload is used to auto create and manage mysql cluster in kubernetes."
spec:
  workloadSettings: |
    {
       "$schema":"http://json-schema.org/draft-07/schema#",
       "type":"object",
       "description":"",
       "required":[
          "spec",
          "config"
       ],
       "properties":{
          "spec":{
             "type":"object",
             "description":"Spec of the custom resource MysqlCluster"
          },
          "config":{
             "type":"string",
             "description":"The config information of MysqlCluster"
          }
       }
    }